---
- name: My task
  hosts: localhost
  connection: local
  vars:
    msg: "hello world"

  tasks:
    - name: "hello world"
      ansible.builtin.command:
        cmd: "echo {{ msg }}"
      register: output
      changed_when: output.rc == 0

    - name: "Check"
      ansible.builtin.debug:
        msg: "{{ output }}"


